---
framework: jest
tier: large
postMerge: 
  pattern: 
    - './cypress/integration/parallax.spec.js'
preMerge:
  pattern:
    - './cypress/integration/parallax.spec.js'
preRun:
     command:
        - yarn install
        - yarn run build
postRun:
     command:
        - yarn --version
version: 2.1
