---
framework: 'jest'
postMerge:
  pattern:
    - './cypress/integration/parallax.spec.js'
preMerge:
  pattern:
    - './cypress/integration/parallax.spec.js'
preRun:
  - yarn install
  - yarn run build
postRun:
  - yarn --version
version: 2.0
